// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7CeCN4ePS-Jl9ehQZq219S_WRUYff1w',
    appId: '1:622054155627:web:267b51a25e06d8370f182e',
    messagingSenderId: '622054155627',
    projectId: 'ninja-brew-crew-62cc9',
    authDomain: 'ninja-brew-crew-62cc9.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-62cc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1eJkDRgfrKSlPBbqdIHpD1xDlRG429Y',
    appId: '1:622054155627:android:654dd454684c818c0f182e',
    messagingSenderId: '622054155627',
    projectId: 'ninja-brew-crew-62cc9',
    storageBucket: 'ninja-brew-crew-62cc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7rxmKki9vjyTleVWhJ9M3PpAVQV47bvA',
    appId: '1:622054155627:ios:bc15dff65e90465b0f182e',
    messagingSenderId: '622054155627',
    projectId: 'ninja-brew-crew-62cc9',
    storageBucket: 'ninja-brew-crew-62cc9.firebasestorage.app',
    iosBundleId: 'com.example.kendrick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7rxmKki9vjyTleVWhJ9M3PpAVQV47bvA',
    appId: '1:622054155627:ios:bc15dff65e90465b0f182e',
    messagingSenderId: '622054155627',
    projectId: 'ninja-brew-crew-62cc9',
    storageBucket: 'ninja-brew-crew-62cc9.firebasestorage.app',
    iosBundleId: 'com.example.kendrick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP7CeCN4ePS-Jl9ehQZq219S_WRUYff1w',
    appId: '1:622054155627:web:651faa7629e6cc450f182e',
    messagingSenderId: '622054155627',
    projectId: 'ninja-brew-crew-62cc9',
    authDomain: 'ninja-brew-crew-62cc9.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-62cc9.firebasestorage.app',
  );
}
